### ISSUE TITLE
Pretrained model release

### ISSUE THREAD

**Issue by wangkaihong** [jiangzhengkai/ProCA#4]
Hi,

Nice work! Could you please share the pretrained model on some other platforms like Google Drive? 

Thanks

**Comment by jiangzhengkai** [comment]
please see Inference Using Pretrained Model, we have published the final model.

**Comment by wangkaihong** [comment]
Hi,

Yes I am aware of the link there, but it's on Baidu Net Disk and it seems not open to user located outside of China for downloading. Could you also upload it on some other platforms so it's more accessible?

Thanks

**Comment by jiangzhengkai** [comment]
@wangkaihong ok, I will upload the model to Google Drive today

**Comment by jiangzhengkai** [comment]
The pretrained models have been uploaded. Close.
